da: Default-A { class: entry }
db: Default-B { class: svc }
dc: Default-C { class: entry }
aa: Alt-A { class: entry }
ab: Alt-B { class: svc }
ac: Alt-C { class: entry }
da -> db: d1
db -> dc: d2
aa -> ab: a1
ab -> ac: a2
