#!/usr/bin/env node
import { Command } from "commander";
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname, basename, extname } from "node:path";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parseStoryFile } from "../story/parser.js";
import { extractStepsFromD2 } from "../story/d2-extractor.js";
import { buildHtml } from "./builder.js";

const program = new Command();
program.name("diascope").description("D2 diagram story tools").version("0.1.0");

// ── build ─────────────────────────────────────────────────────────────────────
program
  .command("build <d2> <story>")
  .description("Render a D2 diagram + story sidecar into a self-contained HTML file")
  .option("-o, --out <file>", "Output HTML file (default: <story-basename>.html)")
  .option("--viewer-bundle <path>", "Path or URL to viewer bundle JS")
  .action((d2Path: string, storyPath: string, opts: { out?: string; viewerBundle?: string }) => {
    const d2Abs = resolve(d2Path);
    const storyAbs = resolve(storyPath);

    // Render D2 → SVG via CLI
    const svgTmp = join(tmpdir(), `diascope-${Date.now()}.svg`);
    try {
      execSync(`d2 "${d2Abs}" "${svgTmp}"`, { stdio: "pipe" });
    } catch (e) {
      console.error("d2 render failed:", (e as Error).message);
      process.exit(1);
    }
    const svgContent = readFileSync(svgTmp, "utf8");

    // Parse story
    const storyContent = readFileSync(storyAbs, "utf8");
    const story = parseStoryFile(storyContent);

    // Warn about node IDs not found in SVG
    warnMissingNodeIds(story, svgContent);

    // Build HTML
    const viewerBundlePath = opts.viewerBundle
      ?? "https://cdn.jsdelivr.net/npm/diascope/dist/diascope.bundle.js";
    const html = buildHtml(svgContent, story, { viewerBundlePath });

    const outPath = opts.out
      ?? resolve(dirname(storyAbs), basename(storyAbs, extname(storyAbs)) + ".html");
    writeFileSync(outPath, html, "utf8");
    console.log(`✓ Written to ${outPath}`);
  });

// ── init ──────────────────────────────────────────────────────────────────────
program
  .command("init <d2>")
  .description("Scaffold a .story.yaml from @step annotations in a D2 file")
  .option("-o, --out <file>", "Output story file (default: <diagram>.story.yaml)")
  .action((d2Path: string, opts: { out?: string }) => {
    const d2Abs = resolve(d2Path);
    const d2Source = readFileSync(d2Abs, "utf8");
    const extracted = extractStepsFromD2(d2Source);

    const outPath =
      opts.out ??
      resolve(dirname(d2Abs), basename(d2Abs, extname(d2Abs)) + ".story.yaml");

    const lines = [
      `# Auto-generated by diascope init — edit titles and body text`,
      `# Node IDs must match D2 source names exactly.`,
      `# See: https://github.com/your-org/d2-story-viewer/blob/main/docs/story-format.md`,
      ``,
      `meta:`,
      `  title: "${basename(d2Abs, extname(d2Abs))}"`,
      `  d2_source: ${basename(d2Abs)}`,
      ``,
      `steps:`,
    ];

    if (extracted.length === 0) {
      lines.push(
        `  # No @step annotations found in ${basename(d2Abs)}.`,
        `  # Add  # @step <id>  comments above nodes/edges in your .d2 file,`,
        `  # or write steps manually following the format in docs/story-format.md`,
        `  - id: step-01`,
        `    tag: "01"`,
        `    title: "TODO: describe this step"`,
        `    nodes: []  # TODO: add D2 node names`,
      );
    } else {
      for (const step of extracted) {
        lines.push(
          `  - id: ${step.id}`,
          `    tag: "${step.id}"`,
          `    title: "TODO: describe ${step.id}"`,
          `    body: ""`,
          `    nodes:`,
          ...(step.nodes ?? []).map((n) => `      - ${n}`),
          ``,
        );
      }
    }

    writeFileSync(outPath, lines.join("\n"), "utf8");
    console.log(`✓ Story scaffold written to ${outPath}`);
    if (extracted.length > 0) {
      console.log(`  Found ${extracted.length} @step annotation(s). Edit titles and body text.`);
    } else {
      console.log(`  No @step annotations found — scaffold written with placeholder step.`);
      console.log(`  Tip: add  # @step <id>  above nodes/edges in ${basename(d2Abs)}`);
    }
  });

program.parse();

function warnMissingNodeIds(story: ReturnType<typeof parseStoryFile>, svgContent: string): void {
  const allNodes = story.steps.flatMap((s) => s.nodes ?? []);
  const missing: string[] = [];
  for (const nodeId of allNodes) {
    const cls = btoa(nodeId);
    if (!svgContent.includes(cls)) missing.push(nodeId);
  }
  if (missing.length > 0) {
    console.warn(`⚠ Node IDs not found in rendered SVG (check D2 names match exactly):`);
    for (const m of missing) console.warn(`  - ${m}`);
  }
}
